module.exports = {
    "JEAN": "Jeans",
    "JEANS": "Jeans",
    "BUZO": "Buzos",
    "BUZOS": "Buzos",
    "REMERA": "Remeras",
    "REMERAS": "Remeras",
    "POLERA": "Remeras",
    "POLERAS": "Remeras",
    "PANTALON": "Pantalones",
    "PANTALONES": "Pantalones",
    "PANTALÓN": "Pantalones",
    "SWEATER": "Sweaters",
    "SWEATERS": "Sweaters",
    "CHOMBA": "Chombas",
    "CHOMBAS": "Chombas",
    "CAMPERA": "Camperas",
    "CAMPERAS": "Camperas",
    "BERMUDA": "Shorts",
    "BERMUDAS": "Shorts",
    "SHORT": "Shorts",
    "SHORTS": "Shorts",
    "BILLETERA": "Sobres",
    "BOTA": "Botas",
    "BOTAS": "Botas",
    "BUFANDA": "Bufandas",
    "BUFANDAS": "Bufandas",
    "CALZA": "Calzas",
    "CALZAS": "Calzas",
    "LEGGING": "Calzas",
    "LEGGINGS": "Calzas",
    "CAMISA": "Camisas",
    "CAMISAS": "Camisas",
    "CARDIGAN": "Cardigans",
    "CARDIGANS": "Cardigans",
    "CHALECO": "Chalecos",
    "CHALECOS": "Chalecos",
    "CINTURON": "Cinturones",
    "CINTURONES": "Cinturones",
    "GORRO": "Gorros",
    "GORROS": "Gorros",
    "JOGGING": "Joggins",
    "JOGGIN": "Joggins",
    "MALLA": "Trajes de baño",
    "MALLAS": "Trajes de baño",
    "ENTERIZA": "Trajes de baño",
    "BIKINI": "Trajes de baño",
    "MOCASIN": "Mocasines",
    "MOCASINES": "Mocasines",
    "MUSCULOSA": "Musculosas",
    "MUSCULOSAS": "Musculosas",
    "PILOTO": "Sacos",
    "SACO": "Sacos",
    "TAPADO": "Sacos",
    "ZAPATILLA": "Zapatillas",
    "BLAZER": "Blazers",
    "BLUSA": "Blusas",
    "BODY": "Ropa interior",
    "CARTERA": "Carteras",
    "CHATITA": "Chatitas",
    "KIMONO": "Kimonos",
    "MOCHILA": "Mochilas",
    "MONO": "Enteritos",
    "PONCHO": "Ponchos",
    "SANDALIA": "Sandalias",
    "TACO": "Stilettos",
    "TOP": "Tops",
    "VESTIDO": "Vestidos",
    "ZAPATO": "Zapatos clásicos",
    "MINIFALDA": "Faldas",
    "FALDA": "Faldas",
    "JARDINERA": "Jardineras",
    "JARDINERO": "Jardineras",
    "BRAZALETE": "Brazaletes",
    "COLLAR": "Collares",
    "CORBATA": "Corbatas",
    "LENTES": "Lentes",
    "MEDIAS": "Medias",
    "SOQUETES": "Medias",
    "PALAZZO": "Palazzos",
    "PALAZZOS": "Palazzos",
    "PIJAMA": "Pijamas",
    "DEPORTIVO": "Ropa deportiva",
    "DEPORTIVA": "Ropa deportiva",
    "TRAJE": "Trajes"
  }