module.exports =
    [
        "47 STREET",
        "ABERCROMBIE & FITCH",
        "A MARIA",
        "A&J",
        "ABSTRACTA",
        "ADIDAS",
        "ADRIANA COSTANTINI",
        "ADRIANNA PAPELL",
        "AEROPOSTALE",
        "AF JEANS",
        "AKIABARA",
        "ALANIZ",
        "ALCOTT",
        "ALERCE",
        "ALFRED DUNNER",
        "ALLO MARTINEZ",
        "AMERICANINO",
        "ANCA Y CO",
        "ANN TAYLOR",
        "APOLOGY",
        "ARMANDO",
        "ASK",
        "ASOS",
        "ATMOSPHERE",
        "AWADA",
        "AY NOT DEAD",
        "AYRES",
        "BALENCIAGA",
        "BANANA REPUBLIC",
        "BASEMENT",
        "BASILOTTA",
        "BATISTELLA",
        "BEIRA RIO",
        "BENDITO VERANO",
        "BERSHKA",
        "BILLABONG",
        "BONNYFRANCO",
        "BOULEVARD",
        "BOWEN",
        "BY DEEP",
        "CACHAREL",
        "CALVIN KLEIN",
        "CARDON",
        "CARO CUORE",
        "CARVEN",
        "CAUTIVA",
        "CENITHO",
        "CHEEKY",
        "CHER",
        "CHRISTIAN DIOR",
        "CHRISTIAN LACROIX",
        "CLARA IBARGUREN",
        "CLOCK HOUSE",
        "CLOSED",
        "CLOTER",
        "CLOUD BREAK",
        "COCCI",
        "COCCOLATI",
        "CODIGO X",
        "CLUSTER WOMEN",
        "COFFEE",
        "COLUMBIA",
        "COMMA",
        "COMMON BLUE",
        "COMO QUIERES",
        "COMPLOT",
        "CONVERSE",
        "COOK",
        "CORTEFIEL",
        "CUESTA BLANCA",
        "CULTURA",
        "DANSKIN",
        "DC",
        "DELUCCA",
        "DENARI RODRIGUEZ",
        "DESIDERATA",
        "DESIGUAL",
        "DIADORA",
        "DIMPLE",
        "DIVIDED",
        "DOO AUSTRALIA",
        "DRESSBARN",
        "DUET",
        "DUFOUR",
        "DULCE CAROLA",
        "DUNES STORES",
        "ELLESSE",
        "ELV",
        "EMBRUJO",
        "ESPRIT",
        "ESTANCIAS CHIRIPÁ",
        "ETAM",
        "EVA MILLER",
        "EVERLAST",
        "EXPRESSO",
        "FABRIZZI",
        "FEBO",
        "FELISA",
        "FENDI",
        "FERRARI",
        "FILA",
        "FIORUCCI",
        "FOR ME",
        "FOREVER 21",
        "FREE PEOPLE",
        "GACEL",
        "GAP",
        "GENOA",
        "GEORGE",
        "GRISINO",
        "GUCCI",
        "GUESS",
        "GUINDA",
        "H&M",
        "HARD ROCK",
        "HEAD",
        "HEBEN",
        "HGT DENIM",
        "HOLLISTER",
        "HUSH PUPPIES",
        "I RUN",
        "IBROO",
        "ID",
        "ILUMINA",
        "INDEX",
        "INDIASTYLE",
        "INEDITA",
        "INQUIETA",
        "INSIDE",
        "ISADORA",
        "JAGUAR",
        "JAZMIN CHEBAR",
        "JONES NEW YORK",
        "JUANITA JO",
        "JULIEN",
        "KAREN OVIANO",
        "KATTO",
        "KAURY",
        "KEEP",
        "KEVINGSTONE",
        "KILL",
        "KIMEIKA",
        "KNAUER",
        "KOSIUKO",
        "KOXIS",
        "LACOSTE",
        "LADY STORK",
        "LADYFIT",
        "LAS OREIRO",
        "LAS PEPAS",
        "LAULA",
        "LE UTTHE",
        "LEE",
        "LEVI´S",
        "LIBERATI",
        "LOLITA",
        "LOTTO",
        "LOVE THIS",
        "LUCERNA",
        "MAA MATERNITY",
        "MAB",
        "MANGO",
        "MAREA",
        "MARKOVA",
        "MARTINA DI TRENTO",
        "MASSIMO CHIESA",
        "MASSIMO DUTTI",
        "MATERIA",
        "MAURO SERGIO",
        "MELOCOTÓN",
        "MERRELL",
        "MICHAEL KORS",
        "MIKAH",
        "MIMO",
        "MIRTA ARMESTO",
        "MOHA",
        "MOJO",
        "MON AMI",
        "MORAVIA",
        "MOSCHINI",
        "MOSSIMO",
        "MOX",
        "MUAA",
        "NAHANA",
        "NAIF",
        "NARE",
        "NASA",
        "NATALIA ANTOLIN",
        "NATASHA",
        "NAUTICA",
        "NEW BALANCE",
        "NEW YORK & COMPANY",
        "NEWPORT",
        "NICOLE MILLER",
        "NIKE",
        "NORMANDIE",
        "NORTH FACE",
        "NOX",
        "NUCLEO",
        "O'NEIL",
        "OCTANE",
        "OLD BRIDGE",
        "OLD NAVY",
        "ONA SAEZ",
        "OPPOSITE",
        "OSHKOSH",
        "OSSIRA",
        "PARFOIS",
        "PARUOLO",
        "PATAGONIA",
        "PAULA CAHEN D'ANVERS",
        "PENGUIN",
        "PERRAMUS",
        "PEUQUE",
        "PIERRE CARDIN",
        "PIETÁ",
        "PLUMITAS",
        "POLO",
        "PORTSAID",
        "POSITANA",
        "PRESTIGE",
        "PRIMARK",
        "PRUNE",
        "PULL&BEAR",
        "PUMA",
        "QUECHUA",
        "QUIKSILVER",
        "RAFAEL GAROFALO",
        "RAIDERS",
        "RAINFOREST",
        "RALPH LAUREN",
        "RAPSODIA",
        "REEBOK",
        "RIE",
        "RIFFLE",
        "RIPCURL",
        "ROCHAS",
        "ROSH",
        "ROXY",
        "RUSTY",
        "SALOMON",
        "SALSA",
        "SANTA CRUZ",
        "SARKANY",
        "SELU",
        "SFERA",
        "SILENZIO",
        "SOANA",
        "SOHO",
        "SOLIDO",
        "SPRINGFIELD",
        "STONE",
        "STRADIVARIUS",
        "SWEET",
        "SYBILLA",
        "SYSTEM",
        "TABATHA",
        "TASCANI",
        "TAVERNITI",
        "TED BODIN",
        "TEX",
        "THIS WEEK",
        "TIMBERLAND",
        "TIRAMISSU",
        "TOMMY HILFIGER",
        "TUBOOS",
        "TUCCI",
        "ULTRA MODA",
        "UMA",
        "UNDER ARMOUR",
        "UNIFORM",
        "UNIVERSITY CLUB",
        "URB",
        "VER",
        "VIAMO",
        "VICTORIA'S SECRET",
        "VITAMINA",
        "VITNIK",
        "VIZZANO",
        "WRANGLER",
        "YAGMOUR",
        "ZARA",
        "ZHOUE"
    ]
